# Using Python 2.7.7 :: Anaconda 2.0.1 (64-bit)

'''
Problem 2 - Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
'''

def main():
    first, second, next = 1, 2, 3
    even_sum = 2

    while next < 4000000:
        next = first + second
        first = second
        second = next

        if next % 2 == 0:
            even_sum += next

    print 'Answer:', even_sum

if __name__ == '__main__':
    main()
